---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:

env:
  CI_LUA_IMAGE: gitea.ttgrules.com/dev/lua:latest

jobs:
  lua-syntax:
    name: Lua Syntax Check
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_LUA_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check Lua file syntax
        shell: bash
        run: |
          set -euo pipefail
          find . -type f -name '*.lua' -not -path './.git/*' -print0 | while IFS= read -r -d '' FILE; do
            echo "Checking ${FILE}"
            luac5.4 -p "${FILE}"
          done

  lua-format:
    name: Lua Format Check
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_LUA_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check Lua formatting
        run: stylua --check .
